#!/bin/sh /etc/rc.common

START=99

IPSEC_SECRETS_FILE=/etc/strongswanInDocker/ipsec.d/ipsec.secrets
IPSEC_CONN_FILE=/etc/strongswanInDocker/ipsec.d/conf/ipsec.conf
IPSEC_DHCP_CONF_FILE=/etc/strongswanInDocker/ipsec.d/strongswan.d/charon/dhcp.conf

. /etc/strongswanInDocker/dockerControl.sh

prepareConfigFiles() {
	if [ -f $IPSEC_DHCP_CONF_FILE ]; then
		return 0
	fi
	7z x -o/etc/strongswanInDocker/ /etc/strongswanInDocker/ipsec.d.7z
}

setup_login() {
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username $1 username
	config_get password $1 password
	[ -n "$username" ] || return 0
	[ -n "$password" ] || return 0
	local ikev2enabled=$(uci -q get strongswanInDocker.@service[0].ikev2enabled)
	if [ "$ikev2enabled" = 1 ]; then
		echo "$username : EAP '$password'" >> $IPSEC_SECRETS_FILE
	fi
	echo "$username : XAUTH '$password'" >> $IPSEC_SECRETS_FILE
}

start() {
	local vt_enabled=$(uci -q get strongswanInDocker.@service[0].enabled)
	[ "$vt_enabled" = 0 ] && return 1
	
	prepareConfigFiles
	
	local vt_clientip=$(uci -q get strongswanInDocker.@service[0].clientip)
	
	local vt_clientdns=$(uci -q get strongswanInDocker.@service[0].clientdns)
	
	local lan_ip=$(uci get network.lan.ipaddr)
	[ -z "$vt_clientdns" ] && local vt_clientdns="8.8.4.4"
	
	local vt_secret=$(uci -q get strongswanInDocker.@service[0].secret)
	
	local useLanDHCP=$(uci -q get strongswanInDocker.@service[0].useLanDHCP)
	
	local lanDHCPServer=$(uci -q get strongswanInDocker.@service[0].lanDHCPServer)
	
	local ikev2enabled=$(uci -q get strongswanInDocker.@service[0].ikev2enabled)
	
	if [ "$useLanDHCP" = 1 ]; then
		#使用局域网IP
		local vt_cfg_rightsourceip="%dhcp";
	else
		local vt_cfg_rightsourceip=$vt_clientip;
	fi
	
	cat > $IPSEC_CONN_FILE <<EOF
# strongswanInDocker.conf - strongSwan IPsec configuration file

# basic configuration

config setup
    # strictcrlpolicy=yes
    uniqueids=never

# Add connections here.

conn xauth_psk
	keyexchange=ikev1
	ike=aes128-sha1-modp2048,aes128-sha1-modp1024,3des-sha1-modp1024,3des-sha1-modp1536
	esp=aes128-sha1,3des-sha1
	left=%defaultroute
	leftauth=psk
	leftsubnet=0.0.0.0/0
	right=%any
	rightauth=psk
	rightauth2=xauth
	rightsourceip=$vt_cfg_rightsourceip
	rightdns=$vt_clientdns
	auto=add
EOF

if [ "$ikev2enabled" = 1 ]; then
	local routerDomain=$(uci -q get strongswanInDocker.@service[0].routerDomain)
cat >> $IPSEC_CONN_FILE <<EOF
conn ikev2-eap
	keyexchange=ikev2
	ike=aes256-sha256-modp1024,3des-sha1-modp1024,aes256-sha1-modp1024,aes256-aes128-sha256-sha1-modp3072-modp2048-modp1024
	esp=aes256-sha256,3des-sha1,aes256-sha1!
	rekey=no
	leftauth=pubkey                           # 服务器端使用公钥方式验证
	leftcert=SERVER.crt  # 证书文件
	leftsendcert=always
	leftid=@$routerDomain                   # 需要和申请CA签发证书中的域名一致
	leftsubnet=0.0.0.0/0
	rightsourceip=$vt_cfg_rightsourceip
	rightauth=eap-mschapv2                    # 客户端使用eap方式验证
	rightsendcert=never
	eap_identity=%any
	rightdns=$vt_clientdns
	auto=add
EOF
fi
	cat > $IPSEC_SECRETS_FILE <<EOF
# $IPSEC_SECRETS_FILE - strongSwan IPsec secrets file
: PSK "$vt_secret"
EOF
if [ "$ikev2enabled" = 1 ]; then
	cat >> $IPSEC_SECRETS_FILE <<EOF
: RSA KEY.key
EOF
fi
	
	config_load strongswanInDocker
	config_foreach setup_login users
	
	local lanDHCPconfig="no"
	if [ "$useLanDHCP" = 1 ]; then
		local lanDHCPconfig="yes"
	fi
	
	cat > $IPSEC_DHCP_CONF_FILE <<EOF
dhcp {

    # Always use the configured server address.
    # force_server_address = no

    # Derive user-defined MAC address from hash of IKE identity and send client
    # identity DHCP option.
    # identity_lease = no

    # Interface name the plugin uses for address allocation.
    interface = br-lan

    # Whether to load the plugin. Can also be an integer to increase the
    # priority of this plugin.
    load = $lanDHCPconfig

    # DHCP server unicast or broadcast IP address.
    server = $lanDHCPServer

    # Use the DHCP server port (67) as source port when a unicast server address
    # is configured.
    # use_server_port = no

}
EOF
	
	startContainer
}

stop() {
	stopContainer
}